<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Álvaro Canalejo-Molero">
<meta name="dcterms.date" content="2023-05-31">

<title>Replication exercise on electoral volatility</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="replication_exercise_files/libs/clipboard/clipboard.min.js"></script>
<script src="replication_exercise_files/libs/quarto-html/quarto.js"></script>
<script src="replication_exercise_files/libs/quarto-html/popper.min.js"></script>
<script src="replication_exercise_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="replication_exercise_files/libs/quarto-html/anchor.min.js"></script>
<link href="replication_exercise_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="replication_exercise_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="replication_exercise_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="replication_exercise_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="replication_exercise_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Replication exercise on electoral volatility</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Álvaro Canalejo-Molero </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 31, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>First, we have to <strong>set up our project</strong>. In the first chunk of code we define <em>knitr</em> parameters, install and load the necessary packages.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Setting the compiling options</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Cleaning the environment</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>())</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Installing packages</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("tidyverse")</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("readxl")</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Loading packages</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) <span class="co"># load the tidyverse programming environment</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl) <span class="co"># for importing xlsx files</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Second, we must <strong>get the data</strong>. We will download it directly from the internet through R. We start by defining the URL where the data is hosted.</p>
<p>The dataset <strong>Party system volatility, regeneration and de-institutionalization in Western Europe (1945–2015)</strong> (Emanuele, 2015) is on a dedicated webpage from the University Luiss Guido Carli. I have copied and pasted the URL to the dataset below. I have also added the link to the dat update for the elections between 2015 and 2022.</p>
<p>By default, any Quarto/RMarkdown document sets the working directory on the same folder where you have downloaded the .Rmd file. We will get this path and add the name of the file that contains the data to it. Therefore, you have to substitute the path in <em>dest</em> by the path of your working directory and leave the same file name at the end of the path.</p>
<p>Finally, we can proceed to download the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Defining the data URL </span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>data_url <span class="ot">&lt;-</span> <span class="st">"https://cise.luiss.it/cise/wp-content/uploads/downloads/2019/03/Dataset-of-Electoral-Volatility-and-its-internal-components-in-Western-Europe-1945-2015.xlsx"</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>update_data_url <span class="ot">&lt;-</span> <span class="st">"http://www.vincenzoemanuele.com/uploads/8/0/5/1/80519836/update_on_elections_2015-2022.xlsx"</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Get working directory path</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">getwd</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "C:/Users/acana/Dropbox/Research/GitHub/teaching/ebpc_unilu2023/14_session14"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the destine file in your working directory</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="do">## in my case</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>dest <span class="ot">&lt;-</span> <span class="st">"C:/Users/acana/Dropbox/Research/GitHub/teaching/ebpc_unilu2023/14_session14/volatility_1945-2015.xlsx"</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>dest_update_data <span class="ot">&lt;-</span> <span class="st">"C:/Users/acana/Dropbox/Research/GitHub/teaching/ebpc_unilu2023/14_session14/update_on_elections.xlsx"</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Download the data to the working directory</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="fu">download.file</span>(data_url, dest, <span class="at">mode=</span><span class="st">"wb"</span>)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="fu">download.file</span>(update_data_url, dest_update_data, <span class="at">mode=</span><span class="st">"wb"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The next step is <strong>opening the data</strong> contained in the .xlsx files.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Open the data</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>vol_data <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"C:/Users/acana/Dropbox/Research/GitHub/teaching/ebpc_unilu2023/14_session14/volatility_1945-2015.xlsx"</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>vol_update_data <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"C:/Users/acana/Dropbox/Research/GitHub/teaching/ebpc_unilu2023/14_session14/update_on_elections.xlsx"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="cleaning-and-merging-the-data" class="level2">
<h2 class="anchored" data-anchor-id="cleaning-and-merging-the-data">Cleaning and merging the data</h2>
<p>Check at the environment tab below. Can you find the vol_data and vol_update_data objects there? Great! That means that we have the data already!</p>
<p>Now, <strong>the first thing to do whenever we analyse a new dataset is taking a first look at its structure</strong>. We will use the tidyverse environment instead of R base functions for the most of it.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Look at the data structure for the elections from 1945 to 2015</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(vol_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 347
Columns: 8
$ Country       &lt;chr&gt; "Austria", "Austria", "Austria", "Austria", "Austria", "~
$ Election_Year &lt;dbl&gt; 1949, 1953, 1956, 1959, 1962, 1966, 1970, 1971, 1975, 19~
$ Election_date &lt;dttm&gt; 1949-10-09, 1953-02-22, 1956-05-13, 1959-05-10, 1962-11~
$ RegV          &lt;dbl&gt; 5.85, 0.00, 0.00, 0.00, 0.00, 1.30, 0.30, 0.00, 0.00, 0.~
$ AltV          &lt;dbl&gt; 6.00, 3.55, 5.45, 2.95, 1.50, 3.20, 6.25, 1.80, 0.45, 1.~
$ OthV          &lt;dbl&gt; 0.35, 0.45, 0.20, 0.05, 0.30, 0.25, 0.05, 0.20, 0.00, 0.~
$ TV            &lt;dbl&gt; 12.20, 4.00, 5.65, 3.00, 1.80, 4.75, 6.60, 2.00, 0.45, 1~
$ ...8          &lt;chr&gt; "Emanuele, V. (2015), Dataset of Electoral Volatility an~</code></pre>
</div>
</div>
<p>So what do we have here? The first thing we notice is that our dataset has <strong>347 rows</strong> (i.e, country-year observations) and <strong>8 columns</strong> (i.e., variables). Each of the rows above contains information on the <strong>name</strong> of the variable, the variable <strong>type</strong> and the <strong>values</strong> of the first number of observations.</p>
<p>Take your time to look at it.</p>
<p>You may notice that the last variable, <strong>…8</strong>, contains information on the dataset citation. We can check this with the commands <em>summary</em> and <em>head</em>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get a summary of the variable "...8"</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(vol_data<span class="sc">$</span>...<span class="dv">8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Length     Class      Mode 
      347 character character </code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Look at the first ten observations</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(vol_data<span class="sc">$</span>...<span class="dv">8</span>, <span class="at">n =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Emanuele, V. (2015), Dataset of Electoral Volatility and its internal components in Western Europe since 1945, Rome: Italian Center for Electoral Studies, http://dx.doi.org/10.7802/1112"
 [2] NA                                                                                                                                                                                         
 [3] NA                                                                                                                                                                                         
 [4] NA                                                                                                                                                                                         
 [5] NA                                                                                                                                                                                         
 [6] NA                                                                                                                                                                                         
 [7] NA                                                                                                                                                                                         
 [8] NA                                                                                                                                                                                         
 [9] NA                                                                                                                                                                                         
[10] NA                                                                                                                                                                                         </code></pre>
</div>
</div>
<p>The command <em>summary</em> tells us that it is a variable of type character (i.e., a string) with length 347, which means that has 347 characters (or letters) in total. The <em>head</em> command confirms that the first observation only contains the dataset citation and the rest is missing values, that in R are represented by <em>NA</em> (i.e., <em>not available</em>). We can remove it and take another look at the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove the variable ...8</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>vol_data <span class="ot">&lt;-</span> vol_data <span class="sc">%&gt;%</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>...<span class="dv">8</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Check the data structure again</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(vol_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 347
Columns: 7
$ Country       &lt;chr&gt; "Austria", "Austria", "Austria", "Austria", "Austria", "~
$ Election_Year &lt;dbl&gt; 1949, 1953, 1956, 1959, 1962, 1966, 1970, 1971, 1975, 19~
$ Election_date &lt;dttm&gt; 1949-10-09, 1953-02-22, 1956-05-13, 1959-05-10, 1962-11~
$ RegV          &lt;dbl&gt; 5.85, 0.00, 0.00, 0.00, 0.00, 1.30, 0.30, 0.00, 0.00, 0.~
$ AltV          &lt;dbl&gt; 6.00, 3.55, 5.45, 2.95, 1.50, 3.20, 6.25, 1.80, 0.45, 1.~
$ OthV          &lt;dbl&gt; 0.35, 0.45, 0.20, 0.05, 0.30, 0.25, 0.05, 0.20, 0.00, 0.~
$ TV            &lt;dbl&gt; 12.20, 4.00, 5.65, 3.00, 1.80, 4.75, 6.60, 2.00, 0.45, 1~</code></pre>
</div>
</div>
<p>Now, we can look at the update data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Look at the data structure for the update on the elections from 2015 to 2022</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(vol_update_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 42
Columns: 7
$ Country       &lt;chr&gt; "Greece", "Portugal", "Switzerland", "Spain", "Cyprus", ~
$ Election_Year &lt;dbl&gt; 2015, 2015, 2015, 2015, 2016, 2016, 2016, 2016, 2017, 20~
$ Election_date &lt;dttm&gt; 2015-09-20, 2015-10-04, 2015-10-18, 2015-12-20, 2016-05~
$ RegV          &lt;dbl&gt; 2.65, 0.60, 0.25, 19.00, 3.60, 5.45, 0.15, 5.80, 0.90, 0~
$ AltV          &lt;dbl&gt; 4.45, 11.45, 4.00, 14.85, 10.55, 18.40, 4.85, 24.90, 21.~
$ OthV          &lt;dbl&gt; 1.30, 1.75, 0.30, 1.65, 1.20, 0.90, 0.50, 0.35, 0.85, 0.~
$ TV            &lt;dbl&gt; 8.40, 13.80, 4.55, 35.50, 15.35, 24.75, 5.50, 31.05, 23.~</code></pre>
</div>
</div>
<p>Great! Both data sets have the same structure already. Therefore, <strong>we can merge them to have an unique dataset with all the observations together</strong>. We can do this with the function from the tidyverse package and then take a glimpse of the new data set <em>m_vol_data</em>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge the data sets</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>m_vol_data <span class="ot">&lt;-</span> <span class="fu">full_join</span>(vol_data, vol_update_data)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Look at the data structure of the merged dataset</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(m_vol_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 389
Columns: 7
$ Country       &lt;chr&gt; "Austria", "Austria", "Austria", "Austria", "Austria", "~
$ Election_Year &lt;dbl&gt; 1949, 1953, 1956, 1959, 1962, 1966, 1970, 1971, 1975, 19~
$ Election_date &lt;dttm&gt; 1949-10-09, 1953-02-22, 1956-05-13, 1959-05-10, 1962-11~
$ RegV          &lt;dbl&gt; 5.85, 0.00, 0.00, 0.00, 0.00, 1.30, 0.30, 0.00, 0.00, 0.~
$ AltV          &lt;dbl&gt; 6.00, 3.55, 5.45, 2.95, 1.50, 3.20, 6.25, 1.80, 0.45, 1.~
$ OthV          &lt;dbl&gt; 0.35, 0.45, 0.20, 0.05, 0.30, 0.25, 0.05, 0.20, 0.00, 0.~
$ TV            &lt;dbl&gt; 12.20, 4.00, 5.65, 3.00, 1.80, 4.75, 6.60, 2.00, 0.45, 1~</code></pre>
</div>
</div>
<p>Ok! So now that we have merged the data, we can make the necessary transformations before the analyses. First, we should transform the variable <em>Country</em> into a factor. This allows us to group the information by each country category, which is definitely more useful than analysing single country-year elections.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Converting character into a factor variables</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>m_vol_data <span class="ot">&lt;-</span> m_vol_data <span class="sc">%&gt;%</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Country =</span> <span class="fu">as.factor</span>(Country))</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Check the data structure again</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(m_vol_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 389
Columns: 7
$ Country       &lt;fct&gt; "Austria", "Austria", "Austria", "Austria", "Austria", "~
$ Election_Year &lt;dbl&gt; 1949, 1953, 1956, 1959, 1962, 1966, 1970, 1971, 1975, 19~
$ Election_date &lt;dttm&gt; 1949-10-09, 1953-02-22, 1956-05-13, 1959-05-10, 1962-11~
$ RegV          &lt;dbl&gt; 5.85, 0.00, 0.00, 0.00, 0.00, 1.30, 0.30, 0.00, 0.00, 0.~
$ AltV          &lt;dbl&gt; 6.00, 3.55, 5.45, 2.95, 1.50, 3.20, 6.25, 1.80, 0.45, 1.~
$ OthV          &lt;dbl&gt; 0.35, 0.45, 0.20, 0.05, 0.30, 0.25, 0.05, 0.20, 0.00, 0.~
$ TV            &lt;dbl&gt; 12.20, 4.00, 5.65, 3.00, 1.80, 4.75, 6.60, 2.00, 0.45, 1~</code></pre>
</div>
</div>
</section>
<section id="exploring-the-data" class="level2">
<h2 class="anchored" data-anchor-id="exploring-the-data">Exploring the data</h2>
<p>Now we can get started with the data analysis!</p>
<p>We can start with some simple visualization. We can use a <strong>histogram</strong> to visualize the distribution of any other numeric variable, such as total volatility. Looking at the data distribution is always useful and one of the first steps of any data analysis. The distribution tells us a few interesting things about the underlying phenomenon we are looking at.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Histogram of Total Volatility</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(m_vol_data, <span class="fu">aes</span>(<span class="at">x =</span> TV)) <span class="sc">+</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="replication_exercise_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><span style="color:red"><strong>What does it tell us here?</strong></span></p>
<p>Even though we learned a few things about volatility in Europe as a whole, the histogram doesn’t tell us anything about cross-country differences. We may want to look at the <strong>distribution within each country</strong> now.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Histogram of Total Volatility by country</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(m_vol_data, <span class="fu">aes</span>(<span class="at">x =</span> TV)) <span class="sc">+</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Country)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="replication_exercise_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Now we can see that there are <strong>important differences</strong> across countries, but also <strong>similarities</strong>. Some of them has very patterned volatility levels while others have wider distributions, although the mean seems to be quite similar in most cases.</p>
<p>In addition, some countries have more identifiable <strong>outliers</strong>, but we don’t know the specific elections. Let’s take a look!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Showing cases where total volatility &gt; 30 only</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>m_vol_data <span class="sc">%&gt;%</span> </span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(TV <span class="sc">&gt;</span> <span class="dv">30</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 x 7
   Country     Election_Year Election_date        RegV  AltV  OthV    TV
   &lt;fct&gt;               &lt;dbl&gt; &lt;dttm&gt;              &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
 1 Greece               2012 2012-05-06 00:00:00 12.8   33.8 1.85   48.5
 2 Iceland              2013 2013-04-27 00:00:00 10.8   23.3 0.500  34.6
 3 Italy                1994 1994-03-27 00:00:00 15.8   20.4 2.95   39.2
 4 Italy                2013 2013-02-25 00:00:00 18.7   16.0 1.90   36.6
 5 Netherlands          2002 2002-05-15 00:00:00  9.3   20.1 1.90   31.3
 6 Spain                1982 1982-10-28 00:00:00  3.5   37.2 3.15   43.8
 7 Spain                2015 2015-12-20 00:00:00 19     14.8 1.65   35.5
 8 Iceland              2016 2016-10-29 00:00:00  5.8   24.9 0.35   31.0
 9 France               2017 2017-06-11 00:00:00 15.3   23.2 2.25   40.7
10 Italy                2022 2022-09-25 00:00:00  5.29  26.9 2.53   34.7</code></pre>
</div>
</div>
<p><span style="color:red"><strong>Does any of these elections sound familiar to you?</strong></span></p>
</section>
<section id="replication-analysis" class="level2">
<h2 class="anchored" data-anchor-id="replication-analysis">Replication analysis</h2>
<p>Now let’s do a little replication exercise!</p>
<p>In their analyses, Chiaramonte and Emanuele (2017) divide the data in three periods: 1946-1968, 1969-1991 and 1992-2015. Then, they measure the average levels of Regeneration Volatility (<em>RegV</em>) for each country on each of the periods to see <strong>what party systems have become more volatile over time</strong> (our first research question) and if RegV has generally increased (our second research question).</p>
<p>We have more observations now, so we can clsuter the latest elections included in the data set update within the their period (1992-2022). This will already provide us woith sone leverage to test whether their conclusions apply later in time.</p>
<p>Also, they display the conclusion of their analysis on a table. We can take a further step by summarising the same information but with a single more visually compelling plot.</p>
<p>To do this, first, we have to create a factor variable that represents each of the periods with a different category.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create period variable</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>m_vol_data <span class="ot">&lt;-</span> m_vol_data <span class="sc">%&gt;%</span> </span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Period =</span> <span class="fu">ifelse</span>(Election_Year <span class="sc">&gt;=</span> <span class="dv">1946</span> <span class="sc">&amp;</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>                         Election_Year <span class="sc">&lt;=</span><span class="dv">1968</span>, <span class="dv">1</span>,</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>                        <span class="fu">ifelse</span>(Election_Year <span class="sc">&gt;=</span> <span class="dv">1969</span> <span class="sc">&amp;</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>                               Election_Year <span class="sc">&lt;=</span><span class="dv">1991</span>, <span class="dv">2</span>,</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>                           <span class="fu">ifelse</span>(Election_Year <span class="sc">&gt;=</span> <span class="dv">1992</span>, <span class="dv">3</span>, <span class="cn">NA</span>))),</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># transform period variable into a factor       </span></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">Period =</span> <span class="fu">factor</span>(Period,</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>                         <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"1"</span>,</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>                                    <span class="st">"2"</span>,</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>                                    <span class="st">"3"</span>),</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>                         <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"1946-1968"</span>,</span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>                                    <span class="st">"1969-1991"</span>,</span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>                                    <span class="st">"1992-2022"</span>)))</span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Get a summary of new the variable "period"</span></span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m_vol_data<span class="sc">$</span>Period)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>1946-1968 1969-1991 1992-2022      NA's 
       99       127       161         2 </code></pre>
</div>
</div>
<p>It seems that there are some missing values, so let’s remove them first!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Removing missing values</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>m_vol_data <span class="ot">&lt;-</span> m_vol_data <span class="sc">%&gt;%</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Period))</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Get a summary of new the variable "period"</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m_vol_data<span class="sc">$</span>Period)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>1946-1968 1969-1991 1992-2022 
       99       127       161 </code></pre>
</div>
</div>
<p>Now we can see that the first period has 99 elections, the second period 127 elections and the third period 161 elections. This already suggest that despite the amounting for a similar time lapse, the last period have witnessed many more electoral repetitions.</p>
<p><strong>Has regeneration volatility also increased?</strong></p>
<p>We can start by visualizing the average levels of RegV and its dispersion by period using <strong>boxplots</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Boxplot of Regeneration Volatility by period</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(m_vol_data, <span class="fu">aes</span>(<span class="at">x =</span> Period, <span class="at">y =</span> RegV)) <span class="sc">+</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">fill =</span> Period))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="replication_exercise_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The boxplots in this case are not too informative, because most elections have low RegV levels. What we can do is <strong>using the logarithmic form of RegV</strong>, which lowers the weight of outliers. As a trade-off, the interpretation of the values becomes less intuitive. However, this is not a problem if what we want to do is see temporal patterns.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Boxplot of the log of Regeneration Volatility by period</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(m_vol_data, <span class="fu">aes</span>(<span class="at">x =</span> Period, <span class="at">y =</span> <span class="fu">log</span>(RegV <span class="sc">+</span> <span class="dv">1</span>))) <span class="sc">+</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">fill =</span> Period)) <span class="sc">+</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"log RegV"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="replication_exercise_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>It seems that <strong>volatility has indeed increased with time!</strong> However, this tells us little about cross-country differences.</p>
<p><strong>Let’s look at the same plot by country.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating a Period variable with shorter labels for aes</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>m_vol_data <span class="ot">&lt;-</span> m_vol_data <span class="sc">%&gt;%</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Period_lab =</span> <span class="fu">factor</span>(Period,</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>                                <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"P1"</span>,</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>                                           <span class="st">"P2"</span>,</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>                                           <span class="st">"P3"</span>)))</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Boxplot of log RegV by period and country</span></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(m_vol_data, <span class="fu">aes</span>(<span class="at">x =</span> Period_lab, <span class="at">y =</span> <span class="fu">log</span>(RegV <span class="sc">+</span> <span class="dv">1</span>))) <span class="sc">+</span></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">fill =</span> Period)) <span class="sc">+</span></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Country) <span class="sc">+</span></span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Adding some aesthetic details</span></span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Period"</span>) <span class="sc">+</span></span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"log RegV"</span>) <span class="sc">+</span></span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">fill=</span><span class="fu">guide_legend</span>(<span class="at">title=</span><span class="st">""</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="replication_exercise_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Great! This single plot summarises even more information than the table of Chiaramonte and Emanuele (2017) and in a more intuitive way.</p>
<p><span style="color:red"><strong>How do you interpret this visualization?</strong></span></p>
<hr>
<p>Finally, let’s fit the relationship between time and RegV with a regression and plot the results on a scatter plot. This is pretty straightforward approach to test whether RegV has increased over time.</p>
<p><span style="color:red"><strong>What do you think of what we see?</strong></span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Scatter plot and regression line of RegV by time</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(m_vol_data, <span class="fu">aes</span>(<span class="at">x =</span> Election_Year, <span class="at">y =</span> <span class="fu">log</span>(RegV <span class="sc">+</span> <span class="dv">1</span>))) <span class="sc">+</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm , <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color=</span><span class="st">"red"</span>, <span class="at">fill=</span><span class="st">"darkgrey"</span>, <span class="at">se=</span><span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>() <span class="sc">+</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"log Regeneration Volatility"</span>) <span class="sc">+</span> </span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Election Year"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="replication_exercise_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>So this is all! I hope this exercise was useful and informative.</p>
I hope you have enjoyed our little walk through R and it encourages you to practice replication over different datasets with R by yourself!
<p>
😊
</p>
<hr>
</section>
<section id="references" class="level1">
<h1>References</h1>
<p>Emanuele, V. (2015). Dataset of Electoral Volatility and its internal components in Western Europe (1945-2015). Rome: Italian Center for Electoral Studies.</p>
<p>Chiaramonte, A., &amp; Emanuele, V. (2017). Party system volatility, regeneration and de-institutionalization in Western Europe (1945–2015). Party Politics, 23(4), 376–388.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>